/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FooterApp: typeof import('./src/components/FooterApp.vue')['default']
    HeaderApp: typeof import('./src/components/HeaderApp.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
